"""add keywords field to articles table

Revision ID: 837428ba03f8
Revises: e5f6a7b8c9d0
Create Date: 2025-11-13 09:23:07.824987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837428ba03f8'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_log', 'admin_email',
               existing_type=sa.VARCHAR(length=200),
               comment='管理员邮箱',
               existing_nullable=False)
    op.alter_column('admin_audit_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='操作类型',
               existing_nullable=False)
    op.alter_column('admin_audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='资源类型',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'resource_id',
               existing_type=sa.INTEGER(),
               comment='资源 ID',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'before_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='操作前数据',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'after_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='操作后数据',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment='IP 地址',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='User-Agent',
               existing_nullable=True)
    op.add_column('articles', sa.Column('keywords', sa.JSON(), nullable=True, comment='文章关键词(3-5个名词,LLM提取)'))
    op.alter_column('blocklist_rules', 'type',
               existing_type=postgresql.ENUM('source', 'keyword', name='ruletype'),
               comment='规则类型',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'pattern',
               existing_type=sa.VARCHAR(length=200),
               comment='匹配模式',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'created_by',
               existing_type=sa.VARCHAR(length=200),
               comment='创建者邮箱',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否启用',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'reason',
               existing_type=sa.VARCHAR(length=500),
               comment='屏蔽原因',
               existing_nullable=True)
    op.alter_column('report_notes', 'report_date',
               existing_type=sa.DATE(),
               comment='报告日期',
               existing_nullable=False)
    op.alter_column('report_notes', 'scope',
               existing_type=postgresql.ENUM('global', 'section', name='notescope'),
               comment='范围',
               existing_nullable=False)
    op.alter_column('report_notes', 'section_key',
               existing_type=sa.VARCHAR(length=100),
               comment='分区键',
               existing_nullable=True)
    op.alter_column('report_notes', 'author_email',
               existing_type=sa.VARCHAR(length=200),
               comment='作者邮箱',
               existing_nullable=False)
    op.alter_column('report_notes', 'content_md',
               existing_type=sa.TEXT(),
               comment='备注内容（Markdown）',
               existing_nullable=False)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment='配置键',
               existing_nullable=False)
    op.alter_column('system_settings', 'value_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配置值(JSON)',
               existing_nullable=True)
    op.alter_column('system_settings', 'description',
               existing_type=sa.TEXT(),
               comment='说明',
               existing_nullable=True)
    op.alter_column('user_preferences', 'user_email',
               existing_type=sa.VARCHAR(length=200),
               comment='用户邮箱',
               existing_nullable=False)
    op.alter_column('user_preferences', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='模板名称',
               existing_nullable=False)
    op.alter_column('user_preferences', 'scope',
               existing_type=postgresql.ENUM('daily', 'article', name='preferencescope'),
               comment='作用范围',
               existing_nullable=False)
    op.alter_column('user_preferences', 'prompt_text',
               existing_type=sa.TEXT(),
               comment='提示词内容',
               existing_nullable=False)
    op.alter_column('user_preferences', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否默认模板',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               server_default=None,
               comment='角色',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否激活',
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               comment='管理员密码哈希',
               existing_nullable=True)
    op.alter_column('watchlist_rules', 'type',
               existing_type=postgresql.ENUM('source', 'keyword', name='ruletype'),
               comment='规则类型',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'pattern',
               existing_type=sa.VARCHAR(length=200),
               comment='匹配模式',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'created_by',
               existing_type=sa.VARCHAR(length=200),
               comment='创建者邮箱',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否启用',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='优先级（数字越大越靠前）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='优先级（数字越大越靠前）',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'created_by',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='创建者邮箱',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'pattern',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='匹配模式',
               existing_nullable=False)
    op.alter_column('watchlist_rules', 'type',
               existing_type=postgresql.ENUM('source', 'keyword', name='ruletype'),
               comment=None,
               existing_comment='规则类型',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='管理员密码哈希',
               existing_nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               server_default=sa.text("'user'::userrole"),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
    op.alter_column('user_preferences', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否默认模板',
               existing_nullable=False)
    op.alter_column('user_preferences', 'prompt_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='提示词内容',
               existing_nullable=False)
    op.alter_column('user_preferences', 'scope',
               existing_type=postgresql.ENUM('daily', 'article', name='preferencescope'),
               comment=None,
               existing_comment='作用范围',
               existing_nullable=False)
    op.alter_column('user_preferences', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='模板名称',
               existing_nullable=False)
    op.alter_column('user_preferences', 'user_email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='用户邮箱',
               existing_nullable=False)
    op.alter_column('system_settings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='说明',
               existing_nullable=True)
    op.alter_column('system_settings', 'value_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='配置值(JSON)',
               existing_nullable=True)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='配置键',
               existing_nullable=False)
    op.alter_column('report_notes', 'content_md',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注内容（Markdown）',
               existing_nullable=False)
    op.alter_column('report_notes', 'author_email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='作者邮箱',
               existing_nullable=False)
    op.alter_column('report_notes', 'section_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='分区键',
               existing_nullable=True)
    op.alter_column('report_notes', 'scope',
               existing_type=postgresql.ENUM('global', 'section', name='notescope'),
               comment=None,
               existing_comment='范围',
               existing_nullable=False)
    op.alter_column('report_notes', 'report_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='报告日期',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'reason',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='屏蔽原因',
               existing_nullable=True)
    op.alter_column('blocklist_rules', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'created_by',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='创建者邮箱',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'pattern',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='匹配模式',
               existing_nullable=False)
    op.alter_column('blocklist_rules', 'type',
               existing_type=postgresql.ENUM('source', 'keyword', name='ruletype'),
               comment=None,
               existing_comment='规则类型',
               existing_nullable=False)
    op.drop_column('articles', 'keywords')
    op.alter_column('admin_audit_log', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='User-Agent',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='IP 地址',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'after_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='操作后数据',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'before_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='操作前数据',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'resource_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='资源 ID',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源类型',
               existing_nullable=True)
    op.alter_column('admin_audit_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('admin_audit_log', 'admin_email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='管理员邮箱',
               existing_nullable=False)
    # ### end Alembic commands ###
