"""Initial schema

Revision ID: c89b568287b0
Revises: 
Create Date: 2025-11-05 22:42:15.410513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89b568287b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False, comment='邮箱地址'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('type', sa.Enum('WHITELIST', 'RECIPIENT', name='recipienttype'), nullable=False, comment='类型'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_recipients_email', 'report_recipients', ['email'], unique=False)
    op.create_index('idx_recipients_type_enabled', 'report_recipients', ['type', 'enabled'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报告日期'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='版本号'),
    sa.Column('overview_summary', sa.Text(), nullable=True, comment='总览摘要'),
    sa.Column('sections_json', sa.JSON(), nullable=True, comment='分区统计JSON'),
    sa.Column('html_body', sa.Text(), nullable=False, comment='邮件正文HTML'),
    sa.Column('html_attachment', sa.Text(), nullable=False, comment='附件HTML'),
    sa.Column('build_meta', sa.JSON(), nullable=True, comment='构建元数据'),
    sa.Column('build_ms', sa.Integer(), nullable=True, comment='构建耗时(毫秒)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_index('idx_reports_date', 'reports', ['report_date'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='信息源名称'),
    sa.Column('type', sa.Enum('RSS', 'STATIC', 'DYNAMIC', name='sourcetype'), nullable=False, comment='信息源类型'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='信息源URL'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('concurrency', sa.Integer(), nullable=True, comment='并发数'),
    sa.Column('timeout_sec', sa.Integer(), nullable=True, comment='超时秒数'),
    sa.Column('parser', sa.String(length=50), nullable=True, comment='解析器名称'),
    sa.Column('region_hint', sa.Enum('DOMESTIC', 'FOREIGN', 'UNKNOWN', name='regionhint'), nullable=True, comment='区域提示'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='信息源ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='文章标题'),
    sa.Column('url', sa.String(length=1000), nullable=False, comment='文章URL'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='采集时间'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='文章正文'),
    sa.Column('content_len', sa.Integer(), nullable=True, comment='正文长度'),
    sa.Column('section', sa.String(length=100), nullable=True, comment='文章分类'),
    sa.Column('region_tag', sa.String(length=20), nullable=True, comment='区域标签:国内/国外/未知'),
    sa.Column('lang', sa.String(length=10), nullable=True, comment='语言'),
    sa.Column('simhash', sa.BigInteger(), nullable=True, comment='SimHash指纹'),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True, comment='规范化URL'),
    sa.Column('dedup_key', sa.String(length=200), nullable=True, comment='去重键'),
    sa.Column('processing_status', sa.Enum('RAW', 'QUEUED', 'RUNNING', 'DONE', 'FAILED', 'PARTIAL', name='processingstatus'), nullable=False, comment='处理状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_articles_processing_status', 'articles', ['processing_status'], unique=False)
    op.create_index('idx_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('idx_articles_simhash', 'articles', ['simhash'], unique=False)
    op.create_index('idx_articles_url', 'articles', ['url'], unique=False)
    op.create_table('delivery_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='报告ID'),
    sa.Column('batch_no', sa.Integer(), nullable=True, comment='批次号'),
    sa.Column('recipients_snapshot', sa.JSON(), nullable=True, comment='收件人快照'),
    sa.Column('message_id', sa.String(length=200), nullable=True, comment='邮件消息ID'),
    sa.Column('status', sa.Enum('OK', 'FAILED', 'PARTIAL', name='deliverystatus'), nullable=False, comment='投递状态'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='错误代码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('sent_at', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_log_report_id', 'delivery_log', ['report_id'], unique=False)
    op.create_index('idx_delivery_log_sent_at', 'delivery_log', ['sent_at'], unique=False)
    op.create_index('idx_delivery_log_status', 'delivery_log', ['status'], unique=False)
    op.create_table('extraction_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('fact', sa.Text(), nullable=False, comment='事实描述'),
    sa.Column('opinion', sa.Text(), nullable=True, comment='观点描述'),
    sa.Column('region', sa.Enum('DOMESTIC', 'FOREIGN', 'UNKNOWN', name='region'), nullable=False, comment='区域'),
    sa.Column('layer', sa.Enum('POLITICS', 'ECONOMY', 'FINTECH_AI', 'FINTECH', 'UNKNOWN', name='layer'), nullable=False, comment='层级'),
    sa.Column('evidence_span', sa.Text(), nullable=True, comment='证据片段'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_items_article_id', 'extraction_items', ['article_id'], unique=False)
    op.create_index('idx_extraction_items_confidence', 'extraction_items', ['confidence'], unique=False)
    op.create_index('idx_extraction_items_region_layer', 'extraction_items', ['region', 'layer'], unique=False)
    op.create_table('extraction_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('provider_hint', sa.String(length=50), nullable=True, comment='Provider提示'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级'),
    sa.Column('attempts', sa.Integer(), nullable=True, comment='尝试次数'),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='queuestatus'), nullable=False, comment='状态'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='最后错误信息'),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('processing_finished_at', sa.DateTime(), nullable=True, comment='完成处理时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('idx_extraction_queue_article_id', 'extraction_queue', ['article_id'], unique=False)
    op.create_index('idx_extraction_queue_priority', 'extraction_queue', ['priority'], unique=False)
    op.create_index('idx_extraction_queue_status', 'extraction_queue', ['status'], unique=False)
    op.create_table('provider_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False, comment='Provider名称'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='模型名称'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='文章ID'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入Token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出Token数'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总Token数'),
    sa.Column('cost', sa.Float(), nullable=True, comment='费用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_usage_article_id', 'provider_usage', ['article_id'], unique=False)
    op.create_index('idx_provider_usage_created_at', 'provider_usage', ['created_at'], unique=False)
    op.create_index('idx_provider_usage_provider', 'provider_usage', ['provider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_usage_provider', table_name='provider_usage')
    op.drop_index('idx_provider_usage_created_at', table_name='provider_usage')
    op.drop_index('idx_provider_usage_article_id', table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index('idx_extraction_queue_status', table_name='extraction_queue')
    op.drop_index('idx_extraction_queue_priority', table_name='extraction_queue')
    op.drop_index('idx_extraction_queue_article_id', table_name='extraction_queue')
    op.drop_table('extraction_queue')
    op.drop_index('idx_extraction_items_region_layer', table_name='extraction_items')
    op.drop_index('idx_extraction_items_confidence', table_name='extraction_items')
    op.drop_index('idx_extraction_items_article_id', table_name='extraction_items')
    op.drop_table('extraction_items')
    op.drop_index('idx_delivery_log_status', table_name='delivery_log')
    op.drop_index('idx_delivery_log_sent_at', table_name='delivery_log')
    op.drop_index('idx_delivery_log_report_id', table_name='delivery_log')
    op.drop_table('delivery_log')
    op.drop_index('idx_articles_url', table_name='articles')
    op.drop_index('idx_articles_simhash', table_name='articles')
    op.drop_index('idx_articles_published_at', table_name='articles')
    op.drop_index('idx_articles_processing_status', table_name='articles')
    op.drop_table('articles')
    op.drop_table('sources')
    op.drop_index('idx_reports_date', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_recipients_type_enabled', table_name='report_recipients')
    op.drop_index('idx_recipients_email', table_name='report_recipients')
    op.drop_table('report_recipients')
    # ### end Alembic commands ###
